# --- Stage 1: Dependencies ---
FROM node:18-alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy package.json dan lock file (yarn.lock atau package-lock.json)
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
# Install dependencies sesuai package manager yang lo pake
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi

# --- Stage 2: Build ---
FROM node:18-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Disable telemetry during build (opsional)
ENV NEXT_TELEMETRY_DISABLED 1

# ARG ini penting buat nerima variabel waktu di-build di Railway nanti
ARG NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL

# Build aplikasi Next.js
RUN npm run build

# --- Stage 3: Runner ---
FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy hasil build yang diperlukan aja
COPY --from=builder /app/public ./public

# Set permission biar aman
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Copy output build (standalone mode lebih kecil)
# Pastiin di next.config.js lo udah nambahin: output: "standalone"
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

# Next.js biasanya jalan di port 3000
EXPOSE 3000

ENV PORT 3000
# set hostname to localhost
ENV HOSTNAME "0.0.0.0"

# Jalanin servernya
CMD ["node", "server.js"]