/**
 * @fileoverview gRPC-Web generated client stub for teluhub.stock
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.33.0
// source: stock.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as stock_pb from './stock_pb'; // proto import: "stock.proto"


export class StockServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorTrackStock = new grpcWeb.MethodDescriptor(
    '/teluhub.stock.StockService/TrackStock',
    grpcWeb.MethodType.SERVER_STREAMING,
    stock_pb.TrackStockRequest,
    stock_pb.StockUpdateResponse,
    (request: stock_pb.TrackStockRequest) => {
      return request.serializeBinary();
    },
    stock_pb.StockUpdateResponse.deserializeBinary
  );

  trackStock(
    request: stock_pb.TrackStockRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<stock_pb.StockUpdateResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/teluhub.stock.StockService/TrackStock',
      request,
      metadata || {},
      this.methodDescriptorTrackStock);
  }

}

